model_name: "slant"
model_version: 0.1.0

# REQUIRED for developer
hardware:
  ntasks: 1
  time: "1:00:00"
  nodes: 1
  mem: "16000mb"
  gpu: 1
  gpumem: "12000mb"
inputs:
- name: "input_dir"
  type: "directory"
  format: "nifti"
outputs:
- name: "output_dir"
  type: "directory"
  format: "nifti"
run:
  tasks: ("download.yaml", "pre_process.yaml", "run_test.yaml", "post_process.yaml", "gen_results.yaml")
analytic:
  name: "slant"
  release_date: "28 November 2018"
  version: "v1.1.0"
  vendor: "Vanderbilt"
  author: "Yuankai Huo"
  description: "Whole brain segmentation"
  Assumptions: "an entire study is dropped on /in"


# OPTIONAL backend
backend:
  server: "Amazon"

# OPTIONAL
input_format:
  modality: "MR"
  SOP:
  MR_options:
    coil: "body"
    pulse: "SSFSE"
    slice_thick: "4"
    spacing: "3"
    weighting: "T2"
    contrast: "none"
    orientation: "COR"
    Bo: "1.5"
    TE: "190"
    TR: "min"
    matrix: "256x256"
    pixel: "1.5"
